pkg-config:
  any: [pkg-config]
python-rospkg:
  any: [rospkg]
python3-rospkg:
  any: [rospkg]
boost:
  any: ['boost']
python-argparse:
  any: []
python-catkin-pkg:
  any: [catkin_pkg]
python3-catkin-pkg:
  any: [catkin_pkg]
python:
  any: ['python']
python3:
  any: ['python']
python3-dev:
  any: ['python']
python-rosdep:
  any: [rosdep]
python3-rosdep:
  any: [rosdep]
python-empy:
  any: [empy]
python3-empy:
  any: [empy]
tinyxml:
  any: [tinyxml]
tinyxml2:
  any: [tinyxml2]
gtest:
  any: [gtest]
cmake:
  any: [cmake]
google-mock:
  any: [gmock]
python-mock:
  any: [mock]
python3-mock:
  any: [mock]
python-nose:
  any: [nose]
python3-nose:
  any: [nose]
python-coverage:
  any: [coverage]
python3-coverage:
  any: [coverage]
libconsole-bridge-dev:
  any: [console_bridge]
python-yaml:
  any: [pyyaml]
python3-yaml:
  any: [pyyaml]
python-setuptools:
  any: [setuptools]
python3-setuptools:
  any: [setuptools]
python3-catkin-pkg-modules:
  any: [catkin_pkg]
python-catkin-pkg-modules:
  any: [catkin_pkg]
python3-rosdep-modules:
  any: [rosdep]
python-rosdep-modules:
  any: ['rosdep']
libboost-system-dev:
  any: ['boost']
libboost-date-time-dev:
  any: ['boost']
libboost-thread-dev:
  any: ['boost']
libpoco-dev:
  any: [poco]
python-gnupg:
  any: [python-gnupg]
python-imaging:
  any: [pillow]
python-crypto:
  any: [pycrypto]
bzip2:
  any: [bzip2]
libssl-dev:
  any: [openssl]
libgpgme-dev:
  unix: [gpgme]
log4cxx:
  any: [log4cxx]
apr:
  any: [apr]
python-netifaces:
  any: [netifaces]
python3-netifaces:
  any: [netifaces]
python-paramiko:
  any: [paramiko]
sbcl:
  win64: []
  unix: [sbcl]
lz4:
  any: [lz4]
python-defusedxml:
  any: [defusedxml]
python-numpy:
  win64: ['numpy']
  unix: ['numpy', 'openblas']
python3-numpy:
  win64: ['numpy']
  unix: ['numpy', 'openblas']
python3-pytest:
  any: [pytest]
python3-rosdistro-modules:
  any: [rosdistro]
python3-lark-parser:
  any: [lark-parser]
cppcheck:
  any: [cppcheck]
python3-mypy:
  any: [mypy]
zlib:
  any: [zlib]
python3-pkg-resources:
  any: []
python3-cryptography:
  any: [cryptography]
python3-ifcfg:
  any: [ifcfg]
python3-flake8:
  any: [flake8]
python3-pytest-mock:
  any: [pytest-mock]
yaml:
  any: [yaml]
asio:
  any: [asio]
git:
  any: [git]
spdlog:
  any: [spdlog]
pcre:
  any: [pcre]
pydocstyle:
  any: [pydocstyle]
libxml2-utils:
  any: [libxml2]
libcunit-dev:
  any: []
uncrustify:
  any: [uncrustify]
python-lxml:
  any: [lxml]
python3-lxml:
  any: [lxml]
openssl:
  any: [openssl]
eigen:
  any: ['eigen', 'openblas']
assimp:
  any: [assimp]
assimp-dev:
  any: [assimp]
libqt5-opengl:
  any: [qt, REQUIRE_OPENGL]
libqt5-opengl-dev:
  any: [qt, REQUIRE_OPENGL]
libqt5-widgets:
  any: [qt, REQUIRE_OPENGL]
curl:
  any: [libcurl]
qtbase5-dev:
  any: [qt]
libqt5-gui:
  any: [qt, REQUIRE_OPENGL]
libqt5-core:
  any: [qt]
libfreetype6-dev:
  any: [freetype]
libfreetype6:
  any: [freetype]
opengl:
  unix: [REQUIRE_OPENGL]
libxaw:
  unix: ['xorg-libxaw']
libx11-dev:
  unix: []
libxrandr:
  unix: [xorg-libxrandr]
libopencv-dev:
  any: [libopencv 3*]
python-opencv:
  any: [opencv 3*]
python3-opencv:
  any: [opencv 3*]
qt5-qmake:
  any: [qt]
python-pydot:
  any: [pydot]
python3-pydot:
  any: [pydot]
python-cairo:
  any: [pycairo]
python3-cairo:
  any: [pycairo]
python-pygraphviz:
  any: [pygraphviz]
python3-pygraphviz:
  any: [pygraphviz]
python-matplotlib:
  any: [matplotlib-base]
python3-matplotlib:
  any: [matplotlib-base]
python-qt5-bindings:
  any: [pyqt]
python3-qt5-bindings:
  any: [pyqt]
python-psutil:
  any: [psutil]
python3-psutil:
  any: [psutil]
python-opengl:
  any: [pyopengl]
python3-opengl:
  any: [pyopengl]
sdl-image:
  any: [sdl2_image]
graphicsmagick:
  any: [graphicsmagick]
libboost-program-options:
  any: ['boost']
sdl:
  any: [sdl2]
libzmq3-dev:
  any: [zeromq]
libboost-program-options-dev:
  any: ['boost-cpp']
libboost-filesystem-dev:
  any: ['boost-cpp']
libogre-dev:
  # ogre has to be pinned here exactly, otherwise GL is missing
  # can't do this in conda_build_config unfortunately
  unix: [ogre 1.10.12 h6508522_3]
  win64: [ogre 1.10]
liburdfdom-dev:
  any: ['urdfdom']
liburdfdom-tools:
  any: ['urdfdom']
liburdfdom-headers-dev:
  any: ['urdfdom_headers']
yaml-cpp:
  any: ['yaml-cpp']
python-wxtools:
  any: ['wxpython']
python-pycryptodome:
  any: ['pycryptodome', 'pycryptodomex']
graphviz:
  any: ['graphviz']
uuid:
  any: [libuuid]
python-sip:
  any: [sip]
cppunit:
  any: [cppunit]
libfcl-dev:
  any: [fcl]
libqhull:
  any: [qhull]
lcov:
  any: [lcov]
glut:
  any: [freeglut]
doxygen:
  any: [doxygen]
libglew-dev:
  any: [glew]
python-pyassimp:
  any: [pyassimp]
python3-pyassimp:
  any: [pyassimp]
libpcl-all-dev:
  any: [pcl]