# this should always be similar to conda-forge's pinnings:
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

pin_run_as_build:
  boost:
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x

# blas
libblas:
  - 3.8 *netlib
libcblas:
  - 3.8 *netlib
liblapack:
  - 3.8.0 *netlib
liblapacke:
  - 3.8.0 *netlib
blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

python:
  # - 2.7.* *_cpython  # [not (aarch64 or ppc64le)]
  - 3.6.* *_cpython
python_impl:
  - cpython
boost:
  - 1.72.0
boost_cpp:
  - 1.72.0
numpy:
  - 1.14
openblas:
  - 0.3.6
openmpi:
  - 4.0